//
//  PaintCodeTutorial.swift
//  PaintCodeTutorial
//
//  Created by Karsten Gresch on 02.10.15.
//  Copyright (c) 2015 Closure One. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//



import UIKit

public class PaintCodeTutorial : NSObject {

    //// Cache

    private struct Cache {
        static let color: UIColor = UIColor(red: 0.481, green: 0.631, blue: 0.860, alpha: 1.000)
        static var imageOfStopwatch: UIImage?
        static var stopwatchTargets: [AnyObject]?
    }

    //// Colors

    public class var color: UIColor { return Cache.color }

    //// Drawing Methods

    public class func drawStopwatch() {

        //// Oval Drawing
        let ovalPath = UIBezierPath(ovalInRect: CGRectMake(15, 30, 220, 220))
        PaintCodeTutorial.color.setFill()
        ovalPath.fill()


        //// Rectangle Drawing
        let rectanglePath = UIBezierPath(rect: CGRectMake(114, 7, 22, 29))
        PaintCodeTutorial.color.setFill()
        rectanglePath.fill()


        //// Bezier Drawing
        let bezierPath = UIBezierPath()
        bezierPath.moveToPoint(CGPointMake(214.14, 30))
        bezierPath.addLineToPoint(CGPointMake(235.36, 51.21))
        bezierPath.addLineToPoint(CGPointMake(221.21, 65.35))
        bezierPath.addCurveToPoint(CGPointMake(216.21, 60.35), controlPoint1: CGPointMake(221.21, 65.35), controlPoint2: CGPointMake(219.1, 63.24))
        bezierPath.addLineToPoint(CGPointMake(204, 60.35))
        bezierPath.addCurveToPoint(CGPointMake(204, 48.14), controlPoint1: CGPointMake(204, 60.35), controlPoint2: CGPointMake(204, 53.76))
        bezierPath.addCurveToPoint(CGPointMake(200, 44.14), controlPoint1: CGPointMake(201.64, 45.78), controlPoint2: CGPointMake(200, 44.14))
        bezierPath.addLineToPoint(CGPointMake(214.14, 30))
        bezierPath.closePath()
        PaintCodeTutorial.color.setFill()
        bezierPath.fill()
    }

    public class func drawStopwatch_Hand() {
        //// General Declarations
        let context = UIGraphicsGetCurrentContext()

        //// Bezier 2 Drawing
        CGContextSaveGState(context)
        CGContextTranslateCTM(context, 125, 110)

        let bezier2Path = UIBezierPath()
        bezier2Path.moveToPoint(CGPointMake(4, -84))
        bezier2Path.addCurveToPoint(CGPointMake(4, -14.46), controlPoint1: CGPointMake(4, -84), controlPoint2: CGPointMake(4, -46.6))
        bezier2Path.addCurveToPoint(CGPointMake(15, 0), controlPoint1: CGPointMake(10.34, -12.71), controlPoint2: CGPointMake(15, -6.9))
        bezier2Path.addCurveToPoint(CGPointMake(4, 14.46), controlPoint1: CGPointMake(15, 6.9), controlPoint2: CGPointMake(10.34, 12.71))
        bezier2Path.addCurveToPoint(CGPointMake(4, 31), controlPoint1: CGPointMake(4, 24.44), controlPoint2: CGPointMake(4, 31))
        bezier2Path.addLineToPoint(CGPointMake(-4, 31))
        bezier2Path.addCurveToPoint(CGPointMake(-4, 14.46), controlPoint1: CGPointMake(-4, 31), controlPoint2: CGPointMake(-4, 24.44))
        bezier2Path.addCurveToPoint(CGPointMake(-15, 0), controlPoint1: CGPointMake(-10.34, 12.71), controlPoint2: CGPointMake(-15, 6.9))
        bezier2Path.addCurveToPoint(CGPointMake(-4, -14.46), controlPoint1: CGPointMake(-15, -6.9), controlPoint2: CGPointMake(-10.34, -12.71))
        bezier2Path.addCurveToPoint(CGPointMake(-4, -84), controlPoint1: CGPointMake(-4, -46.6), controlPoint2: CGPointMake(-4, -84))
        bezier2Path.addLineToPoint(CGPointMake(4, -84))
        bezier2Path.addLineToPoint(CGPointMake(4, -84))
        bezier2Path.closePath()
        UIColor.whiteColor().setFill()
        bezier2Path.fill()

        CGContextRestoreGState(context)
    }

    //// Generated Images

    public class var imageOfStopwatch: UIImage {
        if Cache.imageOfStopwatch != nil {
            return Cache.imageOfStopwatch!
        }

        UIGraphicsBeginImageContextWithOptions(CGSizeMake(250, 250), false, 0)
            PaintCodeTutorial.drawStopwatch()

        Cache.imageOfStopwatch = UIGraphicsGetImageFromCurrentImageContext()
        UIGraphicsEndImageContext()

        return Cache.imageOfStopwatch!
    }

    //// Customization Infrastructure

    @IBOutlet var stopwatchTargets: [AnyObject]! {
        get { return Cache.stopwatchTargets }
        set {
            Cache.stopwatchTargets = newValue
            for target: AnyObject in newValue {
                target.performSelector("setImage:", withObject: PaintCodeTutorial.imageOfStopwatch)
            }
        }
    }

}
